export interface Preset {
  name: string
  description: string
  fasta: string
}

export const PRESETS: Preset[] = [
  {
    name: 'Great Apes',
    description: 'Hominidae mitochondrial DNA',
    fasta: `>Human
GAGCTGGTAGACGGTACCTTAGGGATAACAGGTTAATACCCTCCCGGAG
>Chimp
GAGCTGGTAGACGGTACCTTAGGGATAACAGGTTAATACCCTCCCAGAG
>Gorilla
GAGCTGGTAGACGGTACCTTAGGGATAACAGATTAATACCCTCCCCGAG
>Orangutan
GAGCTGGTAGATGGTACCTTAGGGATAACATGTTAATACCTTCCCCGGG
>Gibbon
GAGTTGGTAGACGGTACTTTGGGGATAACAGGTTAATACCCTCCCCAAG`,
  },
  {
    name: 'Mammals',
    description: 'Cytochrome B across mammals',
    fasta: `>Human
ATGACCAACATCCGAAAAACCCACCCACTAATAAAACCAGTATCATTCCTAGGAATCATCACACTC
>Cow
ATGACCAACATCCGAAAAACTCACCCACTAATAAAACCAATATCATTTTTAGGAATCATTACACTC
>Dog
ATGACCAACATCCGAAAAACCCACCCACTAATAAAACCAATATCATTTTTAGGAATCATTACACTC
>Cat
ATGACCAACATCCGAAAAACTCACCCACTAATAAAACCAATATCATTCCTAGGAATCATTACACTC
>Horse
ATGACCAACATCCGAAAAACCCACCCACTAATAAAACCAATATCATTCCTAGGAATCATTACACTC
>Whale
ATGACCAACATCCGAAAAACCCACCCACTAATAAAACCAATATCATTCCTAGGAATCATTACACTC`,
  },
  {
    name: 'Primates',
    description: 'Mitochondrial D-loop region',
    fasta: `>Human
CCCACAGGTTTAAACCCTAGTTAACTACCCTAACCTTTCCTCCCCTAAATGACTCATCAATCGAT
>Chimpanzee
CCCACAGGTTTAAACCCTAGTTAACTACCCTAACCTTTCCTCCCCTAAATGACTCATCAATCGAC
>Gorilla
CCCACAGGTTTAAACCCTAGTTAACTACCCTAACCTTTCCTCCCCTAAATGACTCATCAATCGCC
>Orangutan
CCCACAGGTTTAAACCCTAGTTAACTACCCTAATCTTTCCTCCCCTAAATGACTCATCAATCGTC
>Bonobo
CCCACAGGTTTAAACCCTAGTTAACTACCCTAACCTTTCCTCCCCTAAATGACTCATCAATCGAT`,
  },
  {
    name: 'Plants',
    description: 'Chloroplast matK gene',
    fasta: `>Arabidopsis
ATGGCTCCATTCTCTTCAAAACTCATCTCTTTACTATTTATAATTTTTATTTTCAAATATGATTC
>Maize
ATGGCTCCATTCTCTTCAAAACTTATCTCTTTACTATTTATAATTTTTATTTTCAAATATGATTC
>Tomato
ATGGCTCCATTCTCTTCAAAACTCATCTCTTTACTATTTATAATTTTCATTTTCAAATATGATTC
>Pine
ATGGCTCCATTCTCTTCAAAACTCATCTCTTAACTATTTATAATTTTTATTTTCAAATATGATTC
>Rice
ATGGCTCCATTCTCTTCAAAACTTATCTCTTTACTATTTATAATTTTTATTTTCAAATATGATTC`,
  },
  {
    name: 'Fish',
    description: 'Cytochrome C oxidase subunit I',
    fasta: `>Zebrafish
ATGGCATCATCTTCAGACTAATTCCCCTCATACTAAAGATATTATCGGACGATGATCAGACAGCC
>Salmon
ATGGCATCATCTTCAGACTAATCCCCCTCATACTAAAGATATCATCGGACGATGATCAGACAGCC
>Tuna
ATGGCATCATCTTCAGACTAATCCCCCTCATACTAAAGATATCATCGGACGATGATCAGACAGCC
>Stickleback
ATGGCATCATCTTCAGACTAATCCCCCTCATACTAAAGATATTATCGGACGATGATCAGACAGCC
>Fugu
ATGGCATCATCTTCAGACTAATCCCCCTCATACTAAAGATATTATCGGACGATGATCAGACAGCC`,
  },
  {
    name: 'Birds',
    description: 'Cytochrome B from avian species',
    fasta: `>Chicken
ATGACCAACATCCGAAAAACGCACCCACTAATAAAACTAACATCATCCTAGGAATCATCACTCTC
>Goose
ATGACCAACATCCGAAAAACACACCCACTAATAAAACTAACATCATCCTAGGAATCATCACTCTC
>Duck
ATGACCAACATCCGAAAAACACACCCACTAATAAAACTAACATCATCCTAGGAATCATCACTCTC
>Ostrich
ATGACCAACATCCGAAAAACCCACCCACTAATAAAACCAATATCATCCTAGGAATCATCACTCTC
>Penguin
ATGACCAACATCCGAAAAACCCACCCACTAATAAAACCAATATCATCCTAGGAATCATCACTCTC`,
  },
]

export function randomSequence(length: number): string {
  const bases = ['A', 'C', 'G', 'T']
  let seq = ''
  for (let i = 0; i < length; i++) seq += bases[Math.floor(Math.random() * 4)]
  return seq
}

export function generateRandomPreset(count: number, seqLen: number): string {
  const names = [
    'Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon',
    'Zeta', 'Eta', 'Theta', 'Iota', 'Kappa',
  ]
  const selected = names.slice(0, count)
  return selected.map(name => `>${name}\n${randomSequence(seqLen)}`).join('\n')
}
